RenamingIssue
SDU-eScience/UCloud pull request #2362
Opened 2021-04-14 19:27 UTC by hschu12

Parent Projects can now always rename subprojects. Projects themself are stil only allowed to rename if parent allows. Fixes #2132
<img width="1148" alt="Screenshot 2021-04-14 at 21 22 11" src="https://user-images.githubusercontent.com/10943804/114767594-1df9c580-9d68-11eb-9030-28bf4371da92.png">
<img width="1086" alt="Screenshot 2021-04-14 at 21 22 17" src="https://user-images.githubusercontent.com/10943804/114767597-1fc38900-9d68-11eb-89fb-585c8c962265.png">

2021-04-15 07:08 UTC, Tiggles commented on frontend-web/webclient/app/Project/Subprojects.tsx
> +                        </Button>
I would keep the `Edit` button, even when editing, just disabling it.

2021-04-15 07:13 UTC, DanThrane requested changes
A few minor changes

2021-04-15 07:13 UTC, DanThrane commented on backend/project-service/src/jvmMain/kotlin/project/rpc/ProjectController.kt
> +                    throw RPCException.fromStatusCode(HttpStatusCode.Forbidden, "Not admin")
I would change both exceptions in this block to a more generic `NotFound` exception.  That way we don't potentially leak information about if a project exists or not.

2021-04-15 07:13 UTC, DanThrane commented on backend/project-service/src/jvmMain/kotlin/project/rpc/ProjectController.kt
> +                    throw RPCException.fromStatusCode(HttpStatusCode.Forbidden, "Not admin")
```suggestion
                    throw RPCException.fromStatusCode(HttpStatusCode.NotFound)
```

2021-04-15 07:13 UTC, DanThrane commented on backend/project-service/src/jvmMain/kotlin/project/rpc/ProjectController.kt
> +            )
```suggestion
            val requestedProject = queries.lookupById(db, request.id) ?: 
                throw RPCException.fromStatusCode(HttpStatusCode.NotFound)
```

2021-04-16 08:30 UTC, Tiggles commented on frontend-web/webclient/app/Project/Subprojects.tsx
> +                        <Button pr={8} pl={8} disabled={isEditingName}>
Couldn't you just write `disabled` here? You have already tested the `isEditingName` boolean above.

2021-04-16 08:43 UTC, Tiggles approved these changes
Frontend part seems fine

2021-04-19 06:50 UTC, DanThrane approved these changes

2021-04-19 06:50 UTC, merged