Issue 3185
SDU-eScience/UCloud pull request #3192
Opened 2022-01-13 10:12 UTC by Tiggles

New:
![image](https://user-images.githubusercontent.com/7610257/149310346-bbf0543a-1725-4b73-bab9-4aa8f68872e3.png)
Old: 
![image](https://user-images.githubusercontent.com/7610257/149310561-e604a07d-e5b5-46f4-a5ee-684da3281db8.png)

2022-01-13 15:05 UTC, DanThrane requested changes
Just did a quick look and the UI looks good to me. But this should replace the old description page entirely and I don't see any code which removes the old page. Just to be clear I am talking about a page such as; https://cloud.sdu.dk/app/applications/details/superset/1.3.0/

2022-01-13 15:18 UTC, Tiggles commented
I was going to ask if that was going to be removed, as the new page seems to have everything the old one has. The only thing it's missing is a better version view:
![image](https://user-images.githubusercontent.com/7610257/149357405-e24216a1-d5a4-452c-8387-48774e2089e7.png)

2022-01-19 07:34 UTC, Tiggles commented
I think that's everything done that we talked about, except a different way of showing you can click recent jobs and I have not merged Machine Type and node count, as these are of different height.

2022-01-25 11:07 UTC, DanThrane approved these changes

2022-01-25 11:07 UTC, merged