Improvements to Admin/Provider
SDU-eScience/UCloud pull request #3503
Opened 2022-06-14 12:12 UTC by xiroV

Fixes to admin/provider page, and functionality to edit/change provider domain and port.

fixes #3482 
fixes #3483 
fixes #3463

2022-06-14 12:17 UTC, DanThrane requested changes
Looks mostly good to me but I have a few changes.

2022-06-14 12:17 UTC, DanThrane commented on backend/accounting-service/src/jvmMain/kotlin/services/providers/ProviderService.kt
> +        val (actor) = actorAndProject
This should be editable by anyone who has "EDIT" rights to the provider (the resource). You can use the `retrieveBulk` call for this.

2022-06-14 12:17 UTC, DanThrane commented on frontend-web/webclient/app/Admin/Providers/Edit.tsx
> +                <RS.Text
I think we should aim for re-using this component across edit and create.

2022-06-14 12:17 UTC, DanThrane commented on frontend-web/webclient/app/UCloud/ProvidersApi.tsx
> +                enabled: (selected, cb) => {
Should only be enabled if you are a UCloud admin (you can use this UI if you have edit rights for the provider)

2022-06-14 12:17 UTC, DanThrane commented on frontend-web/webclient/app/UCloud/ProvidersApi.tsx
> +                text: "Edit",
Should be enabled if you have edit rights for the resource.

2022-06-14 12:22 UTC, Tiggles commented on frontend-web/webclient/app/Admin/Providers/Edit.tsx
> +                <RS.Text
Any reason not to omit this? You can just reuse `provider.data?.specification.id` in `createRequest`, can't you?

2022-06-14 12:25 UTC, Tiggles commented on frontend-web/webclient/app/UCloud/ProvidersApi.tsx
> +    }
@DanThrane, I haven't used it much, but `apiUpdate` should replace the object created here, right?

2022-06-30 13:55 UTC, DanThrane approved these changes

2022-06-30 13:55 UTC, merged