Mount shared
SDU-eScience/UCloud pull request #4103
Opened 2023-12-07 13:53 UTC by hschu12

Added support for mounting shares as root.  Fixes #3965 . 
Also a small change to mount path to better reflect frontend names for Home and Member Files.

2023-12-07 13:57 UTC, Tiggles commented on backend/app-orchestrator-service/src/main/kotlin/services/JobVerificationService.kt
> +            println(newResources)
```suggestion
```

2023-12-07 14:09 UTC, Tiggles commented on backend/app-orchestrator-service/src/main/kotlin/services/JobVerificationService.kt
> +            println("file: $file")
```suggestion
```

2023-12-08 06:52 UTC, DanThrane commented
I have pushed an additional commit. It should take of the bug related to mounting the root of non-shares, but I haven't tested it yet. The arg-builder bug still needs to be resolved.

2023-12-08 11:20 UTC, hschu12 commented on backend/file-orchestrator-service/api/build.gradle.kts
> +    implementation(project(mapOf("path" to ":service-lib-server")))
Automatic import when tries to use metadata service. Forgot to remove.

2023-12-18 06:56 UTC, DanThrane requested changes
Minor changes

2023-12-18 06:56 UTC, DanThrane commented on provider-integration/integration-module/src/main/kotlin/plugins/compute/ucloud/FeatureParameter.kt
> +                    if (components.size == 4 && components[2] == "home") {
```suggestion
                    if (components.size == 4 && components[2] == PathConverter.HOME_DIRECTORY) {
```

2023-12-18 06:56 UTC, DanThrane commented on provider-integration/integration-module/src/main/kotlin/plugins/compute/ucloud/FeatureParameter.kt
> +                    } else if (components.size == 6 && components[4] == "Members' Files"){
```suggestion
                    } else if (components.size == 6 && components[4] == PathConverter.PERSONAL_REPOSITORY){
```

2023-12-18 06:56 UTC, DanThrane approved these changes

2023-12-18 06:56 UTC, merged