Issues june
SDU-eScience/UCloud pull request #4273
Opened 2024-06-18 13:22 UTC by hschu12

Various fixes:
#4248 
#4269
#4235
#4250

2024-06-18 14:17 UTC, Tiggles commented on backend/accounting-service/src/main/kotlin/services/grants/GrantsV2Service.kt
> +                            throw RPCException("Failed to grant resources. Try Again.", HttpStatusCode.UnprocessableEntity)
Is this enough information for the end user? Is this presented to the end user?

2024-06-18 14:24 UTC, Tiggles commented on backend/app-store-service/src/main/kotlin/app/store/services/LogoGenerator.kt
> +            if (cache.compareAndSet(currentCache, stillValidCache)) break
This seems potentially dangerous?

2024-06-18 14:24 UTC, Tiggles commented on backend/app-store-service/src/main/kotlin/app/store/services/LogoGenerator.kt
> +            if (cache.compareAndSet(currentCache, stillValidCache)) break
Note: I can't see the `cache.compareAndSet` method here

2024-06-19 06:12 UTC, DanThrane requested changes
Rollback code needs to be redesigned or removed.

2024-06-19 10:27 UTC, Tiggles commented on frontend-web/webclient/app/Accounting/Allocations.tsx
> +                                shouldShowRetiredAmount: wallet.paysFor.accountingFrequency !== "ONCE" || (alloc.retiredUsage ?? 0) === 0
If retiredUsage is 0, why does it matter that it is shown?

2024-06-19 10:33 UTC, Tiggles commented on frontend-web/webclient/app/Accounting/Allocations.tsx
> +                    retired: number,
Might make more sense to call it "retiredAmount" as it otherwise sounds like a boolean value

2024-06-19 11:09 UTC, Tiggles commented on frontend-web/webclient/app/Accounting/Allocations.tsx
> +                        retired: retired.normalizedBalance,
Might make more sense to call it "retiredAmount" as it otherwise sounds like a boolean value

2024-06-21 11:21 UTC, Tiggles commented on backend/accounting-service/src/main/kotlin/services/accounting/Model.kt
> +    var commited: Boolean = false
```suggestion
    var committed: Boolean = false
```

2024-06-21 11:46 UTC, Tiggles commented
Frontend part seems fine

2024-06-26 08:03 UTC, DanThrane approved these changes

2024-06-26 08:03 UTC, merged