Fixes #4509
SDU-eScience/UCloud pull request #4515
Opened 2024-12-10 13:50 UTC by Tiggles

2024-12-12 13:39 UTC, Tiggles commented
Now also fixes #4503 as I forgot to change branches

2024-12-13 07:01 UTC, DanThrane requested changes

2024-12-13 07:01 UTC, DanThrane commented on frontend-web/webclient/app/Grants/Editor.tsx
> +        durationInMonths: 1
I don't think this was intentional, but let me know if it was.

```suggestion
        durationInMonths: 12
```

2024-12-16 07:05 UTC, DanThrane approved these changes

2024-12-16 07:05 UTC, merged